charge:
  capacity: 9
  teleport-home-cost: 0
  teleport-camp-cost: 0
  teleport-waypoint-cost: 1
  regenerate-time: 24000
  particle-effect: null
token:
  capacity: 1
  activate-waypoint-cost: 8
  particle-effect: null
teleport:
  wait-time: 140
  particle-effect: null
world:
  home:
    - world
  camp:
    - world_nether
    - world_the_end
  waypoint:
    - world
    - world_nether
    - world_the_end
